all:
	##Para usar este compilador escriba: make 1=nombre_archivo
	##Puede probar con el ejemplo incluido escribiendo: make 1=Barbero
	##Cabe mencionar que se recomienda que sus programas terminen con la extension .pfc
	./pfc2 ${1} -o ejercicio/${1}.obj
	./pfc2int ejercicio/${1}